### ISSUE TITLE
Client disconnected when in-dialog Refer subscription terminates

### ISSUE THREAD

**Issue by rhorning** [davehorton/drachtio-server#131] opened 2020-06-01 18:58 UTC
Hello, Dave.

I'm still doing some investigation on my side, but it seems that Drachtio is not handling new in-dialog requests after an in-dialog Refer subscription terminates. This is a follow up of issue [125](https://github.com/davehorton/drachtio-server/issues/125).
Drachtio is not crashing anymore, it can send another in-dialog Refer, but fails to process an in-dialog Notify. The following log shows up:
`ClientController::route_request_inside_dialog - client managing dialog has disconnected`

**Flow**: The scenario simulates a transfer failure followed by a succesful one.
-> The call is established:
UAC -> INVITE ->UAS
UAS -> 200 OK -> UAC
UAC -> ACK -> UAS

-> UAS requests a transfer that fails:
UAS -> REFER -> UAC
UAC -> 202 Accepted for REFER-> UAS
UAC -> NOTIFY (beginning of subscription) -> UAS
UAS -> 200 OK for NOTIFY -> UAC
UAC ->NOTIFY (terminated) -> UAS
UAS -> 200 OK for NOTIFY -> UAC

-> UAS requests a transfer that will succeed:
UAS -> REFER -> UAC
UAC -> 202 Accepted for REFER-> UAS
UAC -> NOTIFY (beginning of subscription) -> UAS
**UAS fails to process Notify**

I'm attaching drachtio's log and the wireshark trace: [notHandlingInDialogReq.zip](https://github.com/davehorton/drachtio-server/files/4712949/notHandlingInDialogReq.zip)
Wireshark filter: _sip.Call-ID == "2da0e521-1edb-1239-08b8-f04da2e57b95"_

**Comment by rhorning** [comment] 2020-06-04 16:11
Hello, @davehorton.

Did you have time to analyze this?

**Comment by davehorton** [comment] 2020-06-08 12:13
sorry, got busy on some projects last week.  Will try to look at this today

**Comment by rhorning** [comment] 2020-06-15 12:11
No problem, @davehorton!
Were you able to analyze it?
Thanks!

**Comment by davehorton** [comment] 2020-06-16 11:50
It does look like it might be an error on the drachtio-srf side.

Could you possibly retest as follows:
- on drachtio-server, set sofia-loglevel to 9
- run your node.js app with `DEBUG=drachtio:*  node app.js` 
- supply the output of both the drachtio log and the console output from the app

**Comment by rhorning** [comment] 2020-06-16 13:29
Here it is: [16_06_20.zip](https://github.com/davehorton/drachtio-server/files/4786842/16_06_20.zip)

Let me know if all the information you need is on these logs.

**Comment by rhorning** [comment] 2020-06-25 21:21
Hello, @davehorton.

Were you able to find something? Let me know if you need any more logs.

**Comment by davehorton** [comment] 2020-06-26 01:53
Its a bit difficult to follow your app logs because it seems like that app is connecting to 4 different servers.  There is clearly a disconnect issued here by the app side of things:
```
 drachtio:socket disconnect: removing socket 9025:54788 +0ms
```
That seems to be the reason that the server can not send the 202 response for the second refer attempt.

Is there any way you can have an app dealing only with the INVITE-OK-ACK-REFER-REFER, ie as shown in the drachtio server log, and get an app log from that?

At this point it seems like either your app is disconnecting, or something in drachtio-srf is.

**Comment by rhorning** [comment] 2020-06-26 17:36
Hello, @davehorton.

You're right, for testing purposes, I needed 4 peers connected to Drachtio.

I was able to create a simple test, apart from the application I was testing, with the same flow.
There is only one peer connected to Drachtio this time (simulating the UAS of the mentioned flow).
The logs should be clearer now.
[26_06_20.zip](https://github.com/davehorton/drachtio-server/files/4838379/26_06_20.zip)

Let me know if they are enough!

**Comment by rhorning** [comment] 2020-07-06 20:25
Hello, @davehorton.

Were you able to find anything with the new logs?
Thanks!

**Comment by davehorton** [comment] 2020-07-06 23:59
Yes, this was helpful.  I think I see what the issue might be.  Should have a fix to test this week

**Comment by CelsoGalo** [comment] 2020-07-09 21:19
Hello @davehorton! Nice to be in touch with you again!

@rhorning works with me, we have a very important release to be done, so I tried to help to investigate this problem.

I found the issue at ClientController::route_request_inside_dialog(). The client dialog reference is being removed when the NOTIFY event with state "terminated" is received. This is indeed valid for explicit notifications for dialogs that were constructed through SUBSCRIBE, but this is not the case when an implicit subscription is obtained after the REFER.

My tests were fine with these changes:

```c++
bool ClientController::route_request_inside_dialog( const string& rawSipMsg, const SipMsgData_t& meta, sip_t const *sip, 
	const string& transactionId, const string& dialogId ) {
	client_ptr client = this->findClientForDialog( dialogId );
	if( !client ) {
		DR_LOG(log_warning) << "ClientController::route_request_inside_dialog - client managing dialog has disconnected: " << dialogId  ;
		
		//TODO: try to find another client providing the same service
		return false ;
	}
	if (string::npos == transactionId.find("unsolicited")) this->addNetTransaction( client, transactionId ) ;

	void (BaseClient::*fn)(const string&, const string&, const string&, const SipMsgData_t&) = &BaseClient::sendSipMessageToClient;
	m_ioservice.post( std::bind(fn, client, transactionId, dialogId, rawSipMsg, meta) ) ;

	// Some conditions may trigger the dialog to be terminated
	bool needRemoveDlg = false;
	
	// if this is a BYE from the network, it ends the dialog 
	string method_name = sip->sip_request->rq_method_name ;
	if (0 == method_name.compare("BYE")) {
		needRemoveDlg = true;
	}
	
	// Dialog subscriptions being terminated will also end the dialog.
	// The exception is the implicit subscription triggered by REFER.
	if (sip_method_notify == sip->sip_request->rq_method && 
		NULL != sip->sip_subscription_state && 
		NULL != sip->sip_subscription_state->ss_substate &&
		NULL != strstr(sip->sip_subscription_state->ss_substate, "terminated")) {
		
		if (NULL != sip->sip_event && (0 == std::strncmp("refer", sip->sip_event->o_type, 5))) {
			DR_LOG(log_debug) << "ClientController::route_request_inside_dialog - implicit subscription termination does not end the dialog " << dialogId;
		} else {
			DR_LOG(log_debug) << "ClientController::route_request_inside_dialog - explicit subscription termination must end the dialog " << dialogId;
			needRemoveDlg = true;
		}
	}

	if (needRemoveDlg) {
		removeDialog( dialogId );
	}
	return true;
}
````

What do you think? I could try to submit a patch if you want, but I believe I have no pull permission for your repository (should I clone it?). You recommended this to me in the past, but I missed the opportunity at that time.

Thanks a lot,
Celso

**Comment by davehorton** [comment] 2020-07-09 21:21
Thanks!  I will make a patch this evening that you could help by testing before I merge it

**Comment by CelsoGalo** [comment] 2020-07-09 21:21
Sure, thanks!

**Comment by davehorton** [comment] 2020-07-10 01:49
can you test the issue-84 branch?

**Comment by CelsoGalo** [comment] 2020-07-10 13:41
Hi @davehorton!

The fix worked fine! I ran a regression for our scenarios (almost 100 test cases) and they all ran fine with the branch issue-84.

Can we have this issue merged soon on master or develop branches?

Thank you so much!

**Comment by davehorton** [comment] 2020-07-10 13:43
Yes, I just have to validate one other fix on that branch and will then merge to develop.  Hopefully today

**Comment by CelsoGalo** [comment] 2020-07-10 16:12
Great, thanks!

**Comment by davehorton** [comment] 2020-07-10 16:20
just pushed to develop.  Could you re-run your test suite on that branch now?

**Comment by CelsoGalo** [comment] 2020-07-10 18:57
Done! All fine on branch develop. Thanks again!!

**Closed** 2020-07-13 13:04 UTC

**Comment by CelsoGalo** [comment] 2020-07-13 14:23
Hi @davehorton, one last comment. When "Event: Refer" is received by Drachtio instead of "Event: refer", then the same problem is seen. I thought this would be handled somewhere in the code, I mean, having the states converted to lower-case already during parsing, but apparently this is not the case.

**Comment by davehorton** [comment] 2020-07-13 23:06
ok please try latest develop branch now
